language: python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: 9.6

env:
  - DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_pec_api

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - psql -c 'create database travis_pec_api;' -U postgres

script:
  - make qa
  - make coverage